### ISSUE TITLE
My Modpack crashes when using Big Reactors

### ISSUE THREAD

**Issue by Luysita** [iguanaman/ThaumcraftMobAspects#3]
Hello, I added Big Reactors to my personal modpack today and it crashes when using Thaumcraft mob aspects. I am using MultiMC launcher and forge 1517.
I disabled Thaumcraft mob aspects from the mod list and now worked fine, but I really want to use both mods.
Is there a fix? Thank you.

http://pastebin.com/cew3fSpb

Big reactors version: BigReactors-0.4.3A
Thaumcraft mob aspects version: ThaumcraftMobAspects-1.7.2-2A

**Comment by iguanaman** [comment]
Hey, this repository is for the 1.6.x version, please direct any issues with future versions here;

https://github.com/Parker8283/ThaumcraftMobAspects
